<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campoSelecioneProfissao</name>
   <tag></tag>
   <elementGuidId>97aa98b1-7268-4ef3-9580-33a320336249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/header/div[2]/div[2]/div[2]/form/div[3]/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1gtu0rj-indicatorContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;page-transition-enter-done&quot;]/div[1]/header[@class=&quot;Header-sc-1fzy4zi-4 dKMMXy&quot;]/div[@class=&quot;Header__CTAArea-sc-1fzy4zi-2 jparvk&quot;]/div[@class=&quot;ModalSignUpContainer-sc-18cyc6j-1 eeuOXc&quot;]/div[@class=&quot;ModalSignUp-sc-15tks8-0 jeeBCn&quot;]/form[1]/div[@class=&quot;Row-sc-1oivv14-0 dmPmMV&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;FormGroup-mushgv-0 jzBDkY&quot;]/div[@class=&quot;css-2b097c-container&quot;]/div[@class=&quot;css-ct6aow-control&quot;]/div[@class=&quot;css-1c6xzql&quot;]/div[@class=&quot;css-1gtu0rj-indicatorContainer&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='__next']/div/div/header/div[2]/div[2]/div[2]/form/div[3]/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione uma profissão'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trabalho em obras ou reformas'])[1]/following::div[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajudante de pedreiro'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Armador'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
